# configuration file for trace_source
# https://github.com/toml-lang/toml
#

output_dir = "output/limassol/"
plot_dir = "plots/limassol"
traj_dir = "trajectories/limassol/" 

geonames = 'standard'

[time]
    begin = '2018-03-14_00'
    end = '2018-03-25_00'
    # time step for which trajectories are calculated
    step = 3
    # duration of each trajectory
    tr_duration = -240

[height]
    top = 12000
    plottop = 10250
    # 'md' mixing depth, '2.0' in km without
    reception = ['md', '2.0', '5.0']

[station]
    name = 'Limassol, Cyprus'
    short_name = 'limassol'
    lat = 34.677
    lon = 33.038
    altitude = 10
